myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tabelog.urls")),
]

tabelog/urls.py
from django.urls import path, include

from tabelog.views import credit, views, booking, like, company
from django.contrib import admin
from django.conf.urls.static import static 
from django.conf import settings





urlpatterns = [
    path('account/', include('allauth.urls')),
    path('', views.StoreView.as_view(), name="home"),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    
    path('store/<int:pk>/', views.StoreDetailView.as_view(), name='store_detail'),
    
    path('booking/store/<int:store_id>/', booking.BookingView.as_view(), name='booking'),
    path('booking/store/booking_cancel/<int:pk>/', booking.BookingCancelView.as_view(), name='booking_cancel'),
    path('booking/store/booking_list/', booking.BookingListView.as_view(), name='booking_list'),
    path('thanks/', booking.ThanksView.as_view(), name='thanks'),

    path('review/store/<int:store_id>/', views.ReviewCreateView.as_view(), name='review_create'),
    path('review_list/', views.ReviewList.as_view(), name='review_list'),
    path('review/store/review_delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review_delete'),
    path('review/store/update/<int:pk>/', views.ReviewUpdateView.as_view(), name='review_update'),
    
    path('like_create/store/<int:store_id>/', like.LikeCreateView.as_view(), name='like_create'),
    path('like_cancel/store/<int:pk>/', like.LikeCancelView.as_view(), name='like_cancel'),
    path('like_list/store/', like.LikeListView.as_view(), name='like_list'),     

    path('credit/register', credit.CreditRegisterView.as_view(), name='credit-register'),
    path('credit/update', credit.CreditUpdateView.as_view(), name='credit-update'),
    path('subscription/cancel', credit.SubscriptionCancelView.as_view(), name='subscription-cancel'),

    path('company/admin/', company.StoreAdminView.as_view(), name='store_admin'),
    path('company/store/create/', company.StoreCreateView.as_view(), name='store_create'),
    path('company/store/edit/<int:pk>/', company.StoreEditView.as_view(), name='store_edit'),
    path('company/store/delete/<int:pk>/', company.StoreDeleteView.as_view(), name='store_delete'),
    path('user_list/', company.UserListView.as_view(), name='user_list'),
    path('category_list/category/create/', company.CategoryCreateView.as_view(), name='category_create'),
    path('category_list/', company.CategoryListView.as_view(), name='category_list'),
    path('category_list/category/delete/<int:pk>/', company.CategoryDeleteView.as_view(), name='category_delete'),
    path('category_list/category/edit/<int:pk>/', company.CategoryEditView.as_view(), name='category_edit'),
    path('company/information/', company.CompanyInfoView.as_view(), name='company_information'),
    path('company/information/update/<int:pk>', company.CompanyInfoUpdateView.as_view(), name='company_information_update'),
]

tabelog/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone





class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name='メールアドレス', unique=True)
    first_name = models.CharField(verbose_name='姓', max_length=20)
    last_name = models.CharField(verbose_name='名', max_length=20)
    telephone_number = models.CharField('電話番号', max_length=30, blank=True)
    post_code = models.CharField('郵便番号', max_length=30, blank=True)
    address = models.CharField('住所', max_length=30, blank=True)
    is_paid = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    stripe_customer_id = models.CharField(max_length=255, blank=True, null=True)
    stripe_card_id = models.CharField(max_length=255, blank=True, null=True)
    stripe_subscription_id = models.CharField(max_length=255, blank=True, null=True)



    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'

SCORE_CHOICES = [
    (1, '★'),
    (2, '★★'),
    (3, '★★★'),
    (4, '★★★★'),
    (5, '★★★★★'),
]

class Category(models.Model):
    id = models.AutoField('カテゴリーID', primary_key=True)
    name = models.CharField('カテゴリー名', max_length=50)

    def __str__(self):
        return self.name

class Store(models.Model):
    id = models.AutoField('店舗ID', primary_key=True)
    name = models.CharField('店舗名', max_length=100)
    address = models.CharField('住所', max_length=100, null=True, blank=True)
    tel = models.CharField('電話番号', max_length=100, null=True, blank=True)
    description = models.TextField('説明', default="", blank=True)
    category = models.ForeignKey(Category, verbose_name='カテゴリー', on_delete=models.PROTECT)
    image = models.ImageField(upload_to='images', verbose_name='イメージ画像', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
   
class Booking(models.Model):
    id = models.AutoField('予約ID', primary_key=True)
    store = models.ForeignKey(Store, on_delete=models.PROTECT)
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    first_name = models.CharField('姓', max_length=100, null=True, blank=True)
    last_name = models.CharField('名', max_length=100, null=True, blank=True)
    tel = models.CharField('電話番号', max_length=100, null=True, blank=True)
    remarks = models.TextField('人数：要望', default="", blank=True)
    start = models.DateTimeField('予約日時', default=timezone.now)
    

    def __str__(self):
        start = timezone.localtime(self.start).strftime('%Y/%m/%d %H:%M')
        return f'{self.first_name}{self.last_name} {start}'

class Review(models.Model):
    id = models.AutoField('レビューID', primary_key=True)
    store = models.ForeignKey(Store, on_delete=models.PROTECT)
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    comment = models.TextField(verbose_name="レビューコメント", blank=False)
    score = models.PositiveSmallIntegerField(verbose_name="レビュースコア", choices=SCORE_CHOICES, default=3)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.store)

    def get_percent(self):
        percent = round(self.score / 5 * 100)
        return percent

class Like(models.Model):
    store = models.ForeignKey(Store, on_delete=models.PROTECT)
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["store", "user"],
                name="like_unique"
            ),
        ]

class Company(models.Model):
    id = models.AutoField('会社ID', primary_key=True)
    name = models.CharField('会社名', max_length=100)
    address = models.CharField('住所', max_length=100, null=True, blank=True)
    tel = models.CharField('電話番号', max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

tabelog/views/booking.py
from datetime import datetime, date, timedelta, time
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.timezone import localtime, make_aware
from django.views.generic import View
from tabelog.models import Store, Booking
from tabelog.forms import BookingForm
from django.views.generic import View, TemplateView, CreateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy


class BookingView(UserPassesTestMixin, CreateView):
    template_name = 'store/booking.html'
    model = Booking
    form_class = BookingForm

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_paid

    def handle_no_permission(self):
        return redirect('home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.store_id = self.kwargs['store_id']
        self.object.user = self.request.user
        self.object.start = datetime.combine(
            form.cleaned_data['start_date'], 
            form.cleaned_data['start_time']
        )
        self.object.save()
        return redirect('thanks')

    def post(self, request, *args, **kwargs):
        self.object = None 
        form = self.form_class(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class BookingCancelView(UserPassesTestMixin, DeleteView):
    template_name = 'store/booking_cancel.html'
    model = Booking
    success_url = reverse_lazy('home')
        
    def test_func(self):
        booking = Booking.objects.get(id=self.kwargs['pk'])
        return self.request.user.is_authenticated and self.request.user.is_paid and booking.user_id == self.request.user.id

    def handle_no_permission(self):
        return redirect('home')

class BookingListView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_paid

    def handle_no_permission(self):
        return redirect('home')

    def get(self, request, *args, **kwargs):
        booking_data = Booking.objects.filter(user_id=request.user.id)

        return render(request, 'store/booking_list.html', {
            'booking_data': booking_data,
        })

    

class ThanksView(TemplateView):
    template_name = 'store/thanks.html'

tabelog/views/company.py
import requests
from myproject import settings
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, CreateView, UpdateView, DeleteView, ListView
from tabelog.models import CustomUser, Store, Category, Company
from tabelog.forms import StoreCreateForm
from django.db.models import Q

class StoreAdminView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_authenticated and not self.request.user.is_staff
    
    def handle_no_permission(self):
        return redirect('home')
    
    def get(self, request):
        
        return render(request, 'store_admin/store_admin.html')

    def post(self, request):
        email = self.request.user.email   
        custom_user = CustomUser.objects.get(email=email)
        custom_user.is_staff = True 
        custom_user.save()

        return redirect('home')


class StoreCreateView(UserPassesTestMixin, CreateView):
    template_name = 'store_admin/storecreate_form.html'
    model = Store
    form = StoreCreateForm()
    fields = ['name', 'address', 'tel', 'description', 'category', 'image']
        
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')
    
    def post(self, request, *args, **kwargs):
        form = StoreCreateForm(request.POST)
        if form.is_valid():
           store = Store()
           store.name = form.cleaned_data['name']
           store.address = form.cleaned_data['address']
           store.tel = form.cleaned_data['tel']
           store.description = form.cleaned_data['description']
           store.category = form.cleaned_data['category']
           if request.FILES:
               store.image = request.FILES.get('image')
           store.save()

           return redirect('home')

        return render(request, 'store_admin/storecreate_form.html', {'form': form})

class StoreEditView(UserPassesTestMixin, UpdateView):
    template_name = 'store_admin/store_edit_form.html'
    model = Store
    form = StoreCreateForm()
    fields = ['name', 'address', 'tel', 'description', 'category', 'image']
    success_url = reverse_lazy('home')
        
    def test_func(self):
        store = Store.objects.get(id=self.kwargs['pk'])
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')

class StoreDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'store_admin/store_delete_form.html'
    model = Store
    success_url = reverse_lazy('home')
        
    def test_func(self):
        store = Store.objects.get(id=self.kwargs['pk'])
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')

class UserListView(UserPassesTestMixin, ListView):
    template_name = 'store_admin/user_list.html'
    model = CustomUser
        
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        active_count = queryset.filter(is_active=True).count()
        paid_count = queryset.filter(is_paid=True).count()

        if self.request.GET.get('q'):
            q = self.request.GET.get('q')
            queryset = queryset.filter(
                Q(first_name__icontains=q) | Q(last_name__icontains=q) | Q(address__icontains=q) | Q(email__icontains=q)
                )
        return queryset
   
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['seach_text'] = self.request.GET.get('q', '')
        ctx['active_count'] = self.get_queryset().filter(is_active=True).count()
        ctx['paid_count'] = self.get_queryset().filter(is_paid=True).count()
        ctx['unpaid_active_count'] = ctx['active_count'] - ctx['paid_count']
        ctx['total_paid_amount'] = ctx['paid_count'] * 300
        return ctx

class CategoryCreateView(UserPassesTestMixin, CreateView):
    template_name = 'store_admin/category_create_form.html'
    model = Category
    fields = ['name']
        
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')
    
    def post(self, request, *args, **kwargs):
        Category.objects.create(
            name = request.POST['name'],
        )
        return redirect('home')

class CategoryListView(UserPassesTestMixin, ListView):
    template_name = 'store_admin/category_list.html'
    model = Category
        
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)

        if self.request.GET.get('q'):
            q = self.request.GET.get('q')
            queryset = queryset.filter(
                Q(name__icontains=q)
                )
        return queryset
   
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["seach_text"] = self.request.GET.get('q', '')
        return ctx

class CategoryDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'store_admin/category_delete_form.html'
    model = Category
    success_url = reverse_lazy('home')
        
    def test_func(self):
        category = Category.objects.get(id=self.kwargs['pk'])
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')

class CategoryEditView(UserPassesTestMixin, UpdateView):
    template_name = 'store_admin/category_edit_form.html'
    model = Category
    fields = ['name']
    success_url = reverse_lazy('home')
        
    def test_func(self):
        category = Category.objects.get(id=self.kwargs['pk'])
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')

class CompanyInfoView(ListView):
    template_name = 'store_admin/company_information.html'
    model = Company
    fields = ['name', 'address', 'tel']

class CompanyInfoUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'store_admin/company_information_update.html'
    model = Company
    fields = ['name', 'address', 'tel']
    success_url = reverse_lazy('home')
        
    def test_func(self):
        company = Company.objects.get(id=self.kwargs['pk'])
        return self.request.user.is_authenticated and self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('home')
    

tabelog/templates/store/booking.html
{% extends 'base.html' %}

{% block title %}予約{% endblock %}
{% block content %}
<form method="post">
  {% csrf_token %}
  
  <div>
      <label for="first_name">名前:</label>
      {{ form.first_name }}
  </div>
  
  <div>
      <label for="last_name">姓:</label>
      {{ form.last_name }}
  </div>
  
  <div>
      <label for="tel">電話番号:</label>
      {{ form.tel }}
  </div>
  
  <div>
      <label for="remarks">人数・備考:</label>
      {{ form.remarks }}
  </div>
  
  <div>
      <label for="start_date">開始日:</label>
      {{ form.start_date }}
  </div>
  
  <div>
      <label for="start_time">開始時間:</label>
      {{ form.start_time }}
  </div>
  
  <button type="submit">予約する</button>
</form>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    <strong>エラーが発生しました：</strong>
    {% for field in form %}
        {% for error in field.errors %}
            <p>{{ error|escape }}</p>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <p>{{ error|escape }}</p>
    {% endfor %}
</div>
{% endif %}


{% endblock %}

tabelog/templates/store/booking_cancel.html
{% extends 'base.html' %}

{% block title %}予約キャンセル{% endblock %}
{% block content %}
<div class="text-center my-5">
  <h1>予約キャンセル</h1>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">予約キャンセル</button>
  </form>


</div>

{% endblock %}

tabelog/templates/store/booking_list.html
{% extends "base.html" %}
{% block title %}予約一覧{% endblock %}
{% block content %}
<h1>予約一覧</h1>

{% for booking in booking_data %}
  <div class="col-md-6 mb-4">
    <div class="card">
      <div class="card-body px-2 py-1">
        <div class="p-4 text-left">
          <h3>{{ booking.store }}店</h3>
          <p>予約日時: {{ booking.start }}</p>
          <p>人数：コメント：{{ booking.remarks }}</p>
          <a href="{% url 'booking_cancel' booking.id %}">予約キャンセル</a>
        </div>
      </div>
    </div>
  </div>
  
  {% empty %}
  <p>まだ予約がありません</p>
  {% endfor %}


{% endblock %}

tabelog/templates/store/like_list.html
{% extends "base.html" %} 
{% block title %}お気に入り一覧{% endblock %}
{% block content %}

<h1>お気に入り一覧</h1>

{% for like in like_data %}
  <div class="col-md-6 mb-4">
    <div class="card">
      <div class="card-body px-2 py-1">
        <div class="p-4 text-left">
          <h3>{{ like.store }}店</h3>
           </form>
        </div>
      </div>
    </div>
  </div>
  
  {% empty %}
  <p>お気に入りがまだありません</p>
  {% endfor %}

{% endblock %}

tabelog/templates/store/review_delete.html
{% extends 'base.html' %}

{% block title %}レビュー削除{% endblock %}
{% block content %}
<div class="text-center my-5">
  <h1>レビュー削除</h1>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">レビュー削除</button>
  </form>


</div>

{% endblock %}

tabelog/templates/store/review_form.html
{% extends 'base.html' %}
{% block title %}レビュー投稿{% endblock %}
{% block content %}
<h1>レビュー投稿</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">投稿する</button>
</form>
{% endblock %}

tabelog/templates/store/store.html
{% extends "base.html" %} 

{% block title %}店舗詳細{% endblock %}
{% block content %}


<div class="text-center my-5">
  <div class="row">
    <div class="col-md-6 mb-4 text-center stafflist">
      {% if store_data.image %}
      <img src="{{ store_data.image.url }}" class="img-fluid" alt="" />
    {% else %}
     <p>画像無し</p>
    {% endif %}
    </div>

    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-body px-2 py-1">
          <div class="p-4 text-left">
            <h3>{{ store_data.name }}</h3>
            <p>平均評価: {{ average }}点/{{ review_count }}件</p>
            <p>住所：{{ store_data.address }}</p>
            <p>TEL：{{ store_data.tel }}</p>
            <p>{{ store_data.description|linebreaksbr }}</p>
            {% if user.is_authenticated %}
            {% if user.is_staff %}
            <a href="{% url 'store_edit' store_data.id %}">店舗編集</a>
            <a href="{% url 'store_delete' store_data.id %}">店舗削除</a>
            {% endif %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <a href="{% url 'review_create' store_data.id %}">レビュー投稿</a>
  <a href="{% url 'booking' store_data.id %}">店舗予約</a>
  {% for review in reviews %}
    <div>{{ review.get_score_display }}</div>
    <div>{{ review.comment }}</div>
    <div>{{ review.user.last_name }}</div>
    <a href="{% url 'review_update' review.id %}">レビュー編集</a>
    <a href="{% url 'review_delete' review.id %}">レビュー削除</a>
  {% endfor %}

  {% if is_like %}
      <form action="{% url 'like_cancel' store_data.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-warning">お気に入り削除</button>
      </form>
  {% else %}
      <form action="{% url 'like_create' store_data.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-secondary">お気に入り</button>
      </form>
{% endif %}


{% endblock %}

tabelog/templates/store/thanks.html
{% extends "base.html" %} {% block content %}

<div class="text-center my-5">
  <h1 class="mb-5">ご予約ありがとうございました。</h1>
  <p class="mb-2">
    担当より予約確定のお電話がありますので、少々お待ちください。
  </p>
  <p class="mb-4">お客様のご来店をスタッフ一同心よりお待ちしております。</p>
  <a class="btn btn-primary" href="/">ホームに戻る</a>
</div>
{% endblock %}